version: 2.1
jobs:
  hello_world:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Echo Hello World
          command: echo "Hello World! This is Pipeline Number:" <<pipeline.number>>
workflows:
  wf_hello_world:
    jobs:
      - hello_world
